# Generated by Django 5.2.1 on 2025-06-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_dietarypreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(default='global', help_text="User's region for ingredient localization.", max_length=10),
        ),
    ]
