# Generated by Django 5.2.1 on 2025-06-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietarypreference',
            name='preferences',
            field=models.TextField(blank=True, default='', help_text="Comma-separated dietary preferences, e.g. 'vegetarian,gluten-free,peanut-allergy'"),
        ),
    ]
