# Generated by Django 5.2.1 on 2025-06-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_date_of_birth_customuser_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='basic_ingredients',
            field=models.TextField(blank=True, help_text="User's basic ingredients as free text (comma-separated or similar)", null=True),
        ),
    ]
