# Generated by Django 5.2.1 on 2025-06-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_basic_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text="User's profile photo.", null=True, upload_to='profile_photos/'),
        ),
    ]
