# Generated by Django 5.2.1 on 2025-08-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0032_recipe_estimated_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated total cost of ingredients for this recipe in francs', max_digits=8, null=True, verbose_name='Estimated Cost'),
        ),
    ]
