"""
Django settings for meal_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Prefer reading SECRET_KEY from environment for production deployments.
# Provide a long fallback for local development only (override in production via env).
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'b6f9e8f4d3c2b1a0987654321fedcba0f1234567890abcdef1234567890abcdef'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('1', 'true', 'yes')

# CSRF Configuration
CSRF_COOKIE_NAME = "csrftoken"
CSRF_HEADER_NAME = "X-CSRFToken"
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True').lower() in ('1', 'true', 'yes')
# Allow JavaScript to read the CSRF cookie so frontend code can copy it into the
# X-CSRFToken header when making cross-site fetch() requests. Default to False
# so developers don't accidentally make the token unreadable; allow override via
# .env (set to 'True' to make cookie HttpOnly).
CSRF_COOKIE_HTTPONLY = os.getenv('CSRF_COOKIE_HTTPONLY', 'False').lower() in ('1', 'true', 'yes')
# For cross-site requests between subdomains (www -> api), SameSite must be
# 'None' and cookies must be Secure. Make SameSite configurable via .env but
# default to 'None' (recommended for production with secure transport).
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'None')

# Session cookie SameSite setting (mirror the CSRF cookie behavior by default)
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'None')
CSRF_USE_SESSIONS = False  # Use cookies instead of sessions for CSRF
CSRF_COOKIE_AGE = 31449600  # 1 year

ALLOWED_HOSTS = os.getenv(
    'ALLOWED_HOSTS',
    '127.0.0.1,localhost,testserver,api.chopsmo.site,www.chopsmo.site'
).split(',')

# Add Render domain if RENDER_EXTERNAL_URL is available
render_url = os.getenv('RENDER_EXTERNAL_URL')
if render_url:
    from urllib.parse import urlparse
    render_domain = urlparse(render_url).netloc
    if render_domain and render_domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(render_domain)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'users',
    'dj_rest_auth',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'planner',
    'recipes',
    'api',
    'billing',
    'django_extensions',
]

MIDDLEWARE = [
    'meal_project.custom_cors_middleware.CustomCorsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'meal_project.middleware.MediaFilesMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'meal_project.log_origin_middleware.LogOriginMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meal_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'meal_project.wsgi.application'
# For Channels / ASGI support, set ASGI_APPLICATION to point to the ASGI entrypoint.
# Create or update meal_project/asgi.py to expose `application` (ProtocolTypeRouter) and
# ensure your server uses the ASGI entrypoint (daphne/uvicorn) instead of WSGI in that case.
ASGI_APPLICATION = 'meal_project.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use DATABASE_URL if available (for Render), otherwise use individual DB_* variables
import dj_database_url

DATABASE_SSL_REQUIRE = os.getenv('DATABASE_SSL_REQUIRE', 'True').lower() in ('1', 'true', 'yes')

default_database_config = dj_database_url.config(
    default=f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT', '5432')}/{os.getenv('DB_NAME')}",
    conn_max_age=600,
    ssl_require=DATABASE_SSL_REQUIRE
)

if default_database_config.get('ENGINE') == 'django.db.backends.sqlite3':
    default_database_config.setdefault('OPTIONS', {}).pop('sslmode', None)

DATABASES = {
    'default': default_database_config
}

# During local test runs it's convenient to avoid connecting to the production
# Postgres (which may be behind VPC/firewall). Allow an explicit env var
# TEST_USE_SQLITE or automatically switch when Django is running tests.
USE_TEST_SQLITE = os.getenv('TEST_USE_SQLITE', '').lower() in ('1', 'true', 'yes')

# Django sets 'TEST' in sys.argv when running tests; detect that as a fallback.
import sys
if (len(sys.argv) > 1 and sys.argv[1] == 'test') or USE_TEST_SQLITE:
    # Use an ephemeral SQLite DB file in the project for tests
    TEST_SQLITE_PATH = os.getenv('TEST_SQLITE_PATH', str(BASE_DIR / 'test_db.sqlite3'))
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': TEST_SQLITE_PATH,
    }
    os.environ.setdefault('DJANGO_ALLOW_ASYNC_UNSAFE', 'true')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# REST Framework throttling for production safety
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle"
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "10/minute",
        "user": "30/minute"
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads)
# https://docs.djangoproject.com/en/5.2/topics/files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configure WhiteNoise to serve media files in production
# Helpful for shared hosting setups where a separate web server for media isn't available
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'

# Channels configuration (optional). If you enable Channels, configure a channel layer
# such as Redis and set CHANNEL_LAYERS accordingly. Example below uses a local Redis.
# For lightweight environments without Redis, use InMemoryChannelLayer
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}

# meal_project/settings.py

# ... (other settings) ...

def _parse_origins(env_var_name: str, default: str):
    """Parse a comma-separated origins env var into a cleaned list.

    Keeps entries trimmed and ignores empty strings. If env var is not set,
    falls back to the provided default string (also comma-separated).
    """
    raw = os.getenv(env_var_name)
    if raw is None:
        raw = default
    # split and strip
    return [p.strip() for p in raw.split(',') if p.strip()]


# Default CORS origins (include both with and without www)
DEFAULT_CORS_ORIGINS = 'http://127.0.0.1:8000,http://localhost:8000,https://www.chopsmo.site,https://chopsmo.site'
CORS_ALLOWED_ORIGINS = _parse_origins('CORS_ALLOWED_ORIGINS', DEFAULT_CORS_ORIGINS)

# Temporarily enabled for frontend compatibility while proper CORS configuration is deployed
# TODO: Tighten this once the AWS domain and subdomains are finalized
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False').lower() in ('1', 'true', 'yes')

# Allow requests from any subdomain of vercel.app
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
]

CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'x-csrftoken',
    'x-requested-with',
    'referer',
    'accept',
    'accept-encoding',
    'accept-language',
    'access-control-request-headers',
    'access-control-request-method',
    'connection',
    'host',
    'origin',
    'user-agent'
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

CORS_ALLOW_CREDENTIALS = True

# Allow all HTTP methods for API endpoints
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'POST',
    'PUT',
]

# Add CSRF trusted origins for frontend (ensure https variants for production)
DEFAULT_CSRF_ORIGINS = 'http://127.0.0.1:5500,http://localhost:5500,https://www.chopsmo.site,https://chopsmo.site,https://api.chopsmo.site'
CSRF_TRUSTED_ORIGINS = _parse_origins('CSRF_TRUSTED_ORIGINS', DEFAULT_CSRF_ORIGINS)

# Make CSRF and session cookies available to subdomains (so frontend on www can
# send cookies to api.chopsmo.site). Use environment variables to override in
# case you prefer explicit values in production.
CSRF_COOKIE_DOMAIN = os.getenv('CSRF_COOKIE_DOMAIN', '.chopsmo.site')
SESSION_COOKIE_DOMAIN = os.getenv('SESSION_COOKIE_DOMAIN', '.chopsmo.site')

SITE_ID = 1

# dj-rest-auth and allauth settings
REST_USE_JWT = False

# New style settings for django-allauth (preferred since Django 5.2)
# Use ACCOUNT_LOGIN_METHODS setting (set-like) to satisfy libraries expecting this value
# and avoid deprecation warnings. If you need custom signup field behavior, override
# via environment variables or admin configuration.
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_EMAIL_VERIFICATION = os.getenv('ACCOUNT_EMAIL_VERIFICATION', 'optional')

# Security defaults (can be overridden by environment variables)
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').lower() in ('1', 'true', 'yes')
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'False').lower() in ('1', 'true', 'yes')
# Default to False to avoid forcing HTTPS during local tests; set to True in production via env
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() in ('1', 'true', 'yes')
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True').lower() in ('1', 'true', 'yes')
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True').lower() in ('1', 'true', 'yes')
ALLOW_INSECURE_COOKIES = os.getenv('ALLOW_INSECURE_COOKIES', 'False').lower() in ('1', 'true', 'yes')

# Honor proto headers from the reverse proxy so Django knows requests arrived via HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Production security overrides (only applied when DEBUG is False)
if not DEBUG:
    # HTTP Strict Transport Security
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').lower() in ('1', 'true', 'yes')
    SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'False').lower() in ('1', 'true', 'yes')

    # Redirect all non-HTTPS requests to HTTPS
    # Allow explicit override via environment variable in production
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() in ('1', 'true', 'yes')

    # Cookies should be secure in production unless explicitly overridden for temporary troubleshooting
    if not ALLOW_INSECURE_COOKIES:
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True
        # In production default to SameSite=None (allow cross-site requests from
        # the frontend domain). This can be overridden via the environment.
        CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'None')
        SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'None')

    # Recommend other secure defaults
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
else:
    # Development-safe defaults (explicit)
    SECURE_HSTS_SECONDS = 0
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    # For local development it's convenient to keep SameSite='Lax' so cookies
    # behave in a forgiving way. These can be overridden via .env when
    # necessary.
    CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'Lax')
    SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')


# Streaming providers
DAILY_API_KEY = os.getenv('DAILY_API_KEY')
DAILY_BASE_URL = os.getenv('DAILY_BASE_URL', 'https://api.daily.co/v1')
DAILY_TIMEOUT = int(os.getenv('DAILY_TIMEOUT', '10'))

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': 'YOUR_GOOGLE_CLIENT_ID',
            'secret': 'YOUR_GOOGLE_CLIENT_SECRET',
            'key': ''
        }
    }
}

# BASIC_INGREDIENTS: Optional override for the default list of basic ingredients assumed to be available in every kitchen.
# To override, uncomment and edit the list below:
# BASIC_INGREDIENTS = [
#     'salt', 'pepper', 'oil', 'water', 'sugar', 'flour', 'butter', 'garlic', 'onion',
#     'vinegar', 'baking powder', 'baking soda', 'soy sauce', 'eggs', 'milk',
# ]


# Alternatively, for very simple local development (less secure for production):
# CORS_ALLOW_ALL_ORIGINS = True