# Generated by Django 5.2.1 on 2025-06-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_approved_recipe_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.JSONField(help_text='List of ingredient names (lowercase)')),
                ('type', models.CharField(choices=[('pair', 'Pair'), ('combination', 'Combination'), ('category', 'Category')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
