# Generated by Django 5.2.1 on 2025-06-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredientsubstitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calories_per_100g',
            field=models.FloatField(default=0, help_text='Calories per 100g'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbs_per_100g',
            field=models.FloatField(default=0, help_text='Carbs per 100g (g)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat_per_100g',
            field=models.FloatField(default=0, help_text='Fat per 100g (g)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein_per_100g',
            field=models.FloatField(default=0, help_text='Protein per 100g (g)'),
        ),
    ]
