# Generated by Django 5.2.1 on 2025-06-09 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_ingredient_calories_per_100g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='preparation',
            field=models.CharField(blank=True, help_text='Preparation notes (e.g., diced, thinly sliced)', max_length=255),
        ),
        migrations.CreateModel(
            name='IngredientSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Synonym or variation name (e.g., 'Coriander', 'Tomatoes')", max_length=100, unique=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='recipes.ingredient')),
            ],
        ),
    ]
