# Generated by Django 5.2.1 on 2025-06-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_tag_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(blank=True, help_text='Recipe source or credit', max_length=255),
        ),
    ]
