# Generated by Django 5.2.1 on 2025-06-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_difficulty_recipe_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('mg', 'milligrams'), ('lb', 'pounds'), ('oz', 'ounces'), ('ml', 'milliliters'), ('l', 'liters'), ('cup', 'cup'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('piece', 'piece'), ('slice', 'slice')], max_length=20),
        ),
    ]
