# Generated by Django 5.2.1 on 2025-06-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=False),  # Remove unique constraint for now
        ),
    ]
