# Generated by Django 5.2.1 on 2025-06-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete: uncheck to hide recipe without removing from DB'),
        ),
    ]
