# Generated by Django 5.2.1 on 2025-06-09 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipe_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who originally created this recipe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this recipe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
