# Generated by Django 5.2.1 on 2025-06-09 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_recipe_created_by_recipe_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who originally created this category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who originally created this cuisine.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuisines_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this cuisine.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuisines_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who originally created this ingredient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this ingredient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who originally created this tag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this tag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
