# Generated by Django 5.2.1 on 2025-06-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_alter_category_created_at_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Basic Ingredient',
                'verbose_name_plural': 'Basic Ingredients',
                'ordering': ['name'],
            },
        ),
    ]
