# Generated by Django 5.2.1 on 2025-06-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_userpantry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicingredient',
            options={'ordering': ['region', 'name'], 'verbose_name': 'Basic Ingredient', 'verbose_name_plural': 'Basic Ingredients'},
        ),
        migrations.AddField(
            model_name='basicingredient',
            name='region',
            field=models.CharField(choices=[('global', 'Global'), ('us', 'United States'), ('uk', 'United Kingdom'), ('fr', 'France'), ('ng', 'Nigeria'), ('in', 'India')], default='global', help_text='Region/culture for this basic ingredient list.', max_length=10),
        ),
    ]
