# Generated by Django 5.2.1 on 2025-06-13 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_alter_ingredient_options_alter_ingredient_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='pending_name',
            field=models.CharField(blank=True, help_text='If ingredient is not in the Ingredient table, store the name here.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(condition=models.Q(('ingredient__isnull', False)), fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(condition=models.Q(('pending_name__isnull', False)), fields=('recipe', 'pending_name'), name='unique_recipe_pending_name'),
        ),
    ]
