# Generated by Django 5.2.1 on 2025-06-28 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_alter_recipeingredient_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='unique_recipe_ingredient',
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='unique_recipe_pending_name',
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('mg', 'milligrams'), ('lb', 'pounds'), ('oz', 'ounces'), ('ml', 'milliliters'), ('l', 'liters'), ('cup', 'cup'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('piece', 'piece'), ('slice', 'slice'), ('clove', 'clove'), ('cloves', 'cloves'), ('pinch', 'pinch'), ('dash', 'dash'), ('handful', 'handful'), ('bunch', 'bunch'), ('can', 'can'), ('bottle', 'bottle'), ('package', 'package')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='pending_name',
        ),
    ]
