# Generated by Django 5.2.1 on 2025-07-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_fix_counter_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='saves',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='views',
        ),
    ]
