# Generated by Django 5.2.1 on 2025-07-09 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_remove_recipe_comments_remove_recipe_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='recipes.recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='recipelike',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_set', to='recipes.recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_set', to='recipes.recipe', verbose_name='Recipe'),
        ),
    ]
