# Generated by Django 5.2.1 on 2025-07-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_fix_database_schema'),
        ('recipes', '0030_update_related_names'),
    ]

    operations = [
    ]
