# Generated by Django 5.2.1 on 2025-07-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_merge_20250709_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated total cost of ingredients for this recipe', max_digits=8, null=True, verbose_name='Estimated Cost'),
        ),
    ]
