# Generated by Django 5.2.1 on 2025-09-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0034_live_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionstepimage',
            name='step_index',
            field=models.PositiveIntegerField(help_text='1-based instruction step index'),
        ),
        migrations.AlterField(
            model_name='livechatmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated total cost of ingredients for this recipe in francs', max_digits=8, null=True, verbose_name='Estimated Cost'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ordering for gallery images'),
        ),
    ]
