# Generated by Django 5.2.1 on 2025-10-18 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0036_websockettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg', models.DecimalField(decimal_places=2, help_text='Price per kilogram in local currency (e.g., CFA)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='recipes.ingredient')),
            ],
        ),
    ]
