# Generated by Django 5.2.1 on 2025-10-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0037_ingredientprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='default_unit_weight_g',
            field=models.FloatField(blank=True, help_text='Default grams for a single unit (e.g., grams per piece or per cup) used for cost estimation of non-weight units', null=True, verbose_name='Default unit weight (g)'),
        ),
    ]
