# Generated by Django 5.2.1 on 2025-06-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealplan',
            options={'ordering': ['date'], 'verbose_name': 'Meal Plan', 'verbose_name_plural': 'Meal Plans'},
        ),
    ]
